app/admin/views.py
from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from flask_rq import get_queue

from app import db
from app.admin.forms import (
    ChangeAccountTypeForm,
    ChangeUserEmailForm,
    InviteUserForm,
    NewUserForm,
)
from app.decorators import admin_required
from app.email import send_email
from app.models import EditableHTML, Role, User

admin = Blueprint('admin', __name__)


@admin.route('/')
@login_required
@admin_required
def index():
    """Admin dashboard page."""
    return render_template('admin/index.html')


@admin.route('/new-user', methods=['GET', 'POST'])
@login_required
@admin_required
def new_user():
    """Create a new user."""
    form = NewUserForm()
    if form.validate_on_submit():
        user = User(
            role=form.role.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('User {} successfully created'.format(user.full_name()),
              'form-success')
    return render_template('admin/new_user.html', form=form)


@admin.route('/invite-user', methods=['GET', 'POST'])
@login_required
@admin_required
def invite_user():
    """Invites a new user to create an account and set their own password."""
    form = InviteUserForm()
    if form.validate_on_submit():
        user = User(
            role=form.role.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data)
        db.session.add(user)
        db.session.commit()
        token = user.generate_confirmation_token()
        invite_link = url_for(
            'account.join_from_invite',
            user_id=user.id,
            token=token,
            _external=True)
        get_queue().enqueue(
            send_email,
            recipient=user.email,
            subject='You Are Invited To Join',
            template='account/email/invite',
            user=user,
            invite_link=invite_link,
        )
        flash('User {} successfully invited'.format(user.full_name()),
              'form-success')
    return render_template('admin/new_user.html', form=form)


@admin.route('/users')
@login_required
@admin_required
def registered_users():
    """View all registered users."""
    users = User.query.all()
    roles = Role.query.all()
    return render_template(
        'admin/registered_users.html', users=users, roles=roles)


@admin.route('/user/<int:user_id>')
@admin.route('/user/<int:user_id>/info')
@login_required
@admin_required
def user_info(user_id):
    """View a user's profile."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    return render_template('admin/manage_user.html', user=user)


@admin.route('/user/<int:user_id>/change-email', methods=['GET', 'POST'])
@login_required
@admin_required
def change_user_email(user_id):
    """Change a user's email."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    form = ChangeUserEmailForm()
    if form.validate_on_submit():
        user.email = form.email.data
        db.session.add(user)
        db.session.commit()
        flash('Email for user {} successfully changed to {}.'.format(
            user.full_name(), user.email), 'form-success')
    return render_template('admin/manage_user.html', user=user, form=form)


@admin.route(
    '/user/<int:user_id>/change-account-type', methods=['GET', 'POST'])
@login_required
@admin_required
def change_account_type(user_id):
    """Change a user's account type."""
    if current_user.id == user_id:
        flash('You cannot change the type of your own account. Please ask '
              'another administrator to do this.', 'error')
        return redirect(url_for('admin.user_info', user_id=user_id))

    user = User.query.get(user_id)
    if user is None:
        abort(404)
    form = ChangeAccountTypeForm()
    if form.validate_on_submit():
        user.role = form.role.data
        db.session.add(user)
        db.session.commit()
        flash('Role for user {} successfully changed to {}.'.format(
            user.full_name(), user.role.name), 'form-success')
    return render_template('admin/manage_user.html', user=user, form=form)


@admin.route('/user/<int:user_id>/delete')
@login_required
@admin_required
def delete_user_request(user_id):
    """Request deletion of a user's account."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    return render_template('admin/manage_user.html', user=user)


@admin.route('/user/<int:user_id>/_delete')
@login_required
@admin_required
def delete_user(user_id):
    """Delete a user's account."""
    if current_user.id == user_id:
        flash('You cannot delete your own account. Please ask another '
              'administrator to do this.', 'error')
    else:
        user = User.query.filter_by(id=user_id).first()
        db.session.delete(user)
        db.session.commit()
        flash('Successfully deleted user %s.' % user.full_name(), 'success')
    return redirect(url_for('admin.registered_users'))


@admin.route('/_update_editor_contents', methods=['POST'])
@login_required
@admin_required
def update_editor_contents():
    """Update the contents of an editor."""

    edit_data = request.form.get('edit_data')
    editor_name = request.form.get('editor_name')

    editor_contents = EditableHTML.query.filter_by(
        editor_name=editor_name).first()
    if editor_contents is None:
        editor_contents = EditableHTML(editor_name=editor_name)
    editor_contents.value = edit_data

    db.session.add(editor_contents)
    db.session.commit()

    return 'OK', 200

app/templates/macros/check_password.html
{% macro password_check(field, level) %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.2.0/zxcvbn.js"></script>
<script>
  $('#submit').attr('disabled', true);
  $('#{{ field }}').after('<progress value="0" max="4" id="password-strength-meter"></progress><p id="password-strength-text"></p>');
  if(!$('#{{ field }}').length) {
    $('#submit').attr('disabled', false);
  }
  var strength = {
    0: "Bad",
    1: "Okay",
    2: "Good",
    3: "Very Good",
    4: "Strong"
  }
  var meter = document.getElementById('password-strength-meter');
  var text = $('#password-strength-text');

  $('#{{ field }}').keyup(function() {
    var result = zxcvbn($(this).val());
    // Update the password strength meter
    meter.value = result.score;
    if(result.score >= {{ level }}) {
      $('#submit').attr('disabled', false);
    } else {
      $('#submit').attr('disabled', true);
    }
    // Update the text indicator
    if ($(this).val() !== "") {
      $(text).html("Strength: " + strength[result.score]); 
    } else {
      $(text).html("");
    }
  });
</script>
<style>
  progress {
    /* Reset the default appearance */
    -webkit-appearance: none;
       -moz-appearance: none;
            appearance: none;

    margin: 10 auto 1em;
    width: 100%;
    height: 0.5em;
    background-color: rgba(0, 0, 0, 0.1);
  }

  /* Chrome */
  progress::-webkit-progress-value {
    background: rgba(0, 0, 0, 0.1); 
  }

   /* Webkit based browsers */
  progress[value^="1"]::-webkit-progress-value { background-color: red; }
  progress[value^="2"]::-webkit-progress-value { background-color: yellow; }
  progress[value^="3"]::-webkit-progress-value { background-color: orange; }
  progress[value^="4"]::-webkit-progress-value { background-color: green; }


  /* Gecko based browsers */
  progress[value^="1"]::-moz-progress-bar { background-color: red; }
  progress[value^="2"]::-moz-progress-bar { background-color: yellow; }
  progress[value^="3"]::-moz-progress-bar { background-color: orange; }
  progress[value^="4"]::-moz-progress-bar { background-color: green; }
</style>

{% endmacro %}

app/templates/macros/form_macros.html
{# WTForms macros heavily inspired by Flask-Bootstrap.
 # Consult their docs if you are confused about anything here:
 # http://pythonhosted.org/Flask-Bootstrap/macros.html?highlight=quick_form#quick_form #}

{# Render a flask.ext.wtforms.Form object.
   Parameters:
        form          – The form to output.
        method        – <form> method attribute (default 'POST')
        extra_classes – The classes to add to the <form>.
        enctype       – <form> enctype attribute. If None, will automatically be set to
                        multipart/form-data if a FileField is present in the form. #}
{% macro render_form(form, method='POST', extra_classes='', enctype=None) %}
    {% set flashes = {
        'error':   get_flashed_messages(category_filter=['form-error']),
        'warning': get_flashed_messages(category_filter=['form-check-email']),
        'info':    get_flashed_messages(category_filter=['form-info']),
        'success': get_flashed_messages(category_filter=['form-success'])
    } %}

    {{ begin_form(form, flashes, method=method, extra_classes=extra_classes, enctype=enctype) }}
        {% for field in form if not (is_hidden_field(field) or field.type == 'SubmitField') %}
            {{ render_form_field(field) }}
        {% endfor %}

        {{ form_message(flashes['error'], header='Something went wrong.', class='error') }}
        {{ form_message(flashes['warning'], header='Check your email.', class='warning') }}
        {{ form_message(flashes['info'], header='Information', class='info') }}
        {{ form_message(flashes['success'], header='Success!', class='success') }}

        {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
            {{ render_form_field(field) }}
        {% endfor %}

    {{ end_form(form) }}
{% endmacro %}

{# Set up the form, including hidden fields and error states #}
{% macro begin_form(form, flashes, method='POST', extra_classes='', enctype=None) %}
    {# Set proper enctype #}
    {% if enctype is none and (form | selectattr('type', 'equalto', 'FileField') | list | length > 0) %}
        {% set enctype = 'multipart/form-data' %}
    {% else %}
        {% set enctype = '' %}
    {% endif %}

    <form action="" method="{{ method }}" enctype="{{ enctype }}" class="ui form {{ extra_classes }}
        {% if form.errors or flashes['error'] %} error
        {% elif flashes['warning'] %} warning
        {% elif flashes['info'] %} info
        {% elif flashes['success'] %} success
        {% endif %}">
    {{ form.hidden_tag() }}
{% endmacro %}

{# Mirrors begin_form #}
{% macro end_form(form) %}
    </form>
{% endmacro %}

{# Render a message for the form #}
{% macro form_message(messages, header=none, class='') %}
    {% if messages %}
        <div class="ui {{ class }} message">
            {% if header is not none %}
                <div class="header">{{ header }}</div>
            {% endif %}
            {% if messages %}
                <ul class="list">
                    {% for message in messages %}
                        <li>{{ message | safe }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    {% endif %}
{% endmacro %}

{# Render a field for the form #}
{% macro render_custom_select(field) %}
    {{ field.label }}
    {% if field.description %}
        <div class="ui pointing below label">
            {{ field.description }}
        </div>
    {% endif %}
    <div id="{{field.name}}" class="ui fluid {% if field.multiple %}multiple {% endif %}search selection dropdown">
        {{ field() }}
        <i class="dropdown icon"></i>
        <div class="default text">{{field.label.text}}</div>
        <div class="menu">
            {% for choice in field.choices %}
                <div class="item">{{choice}}</div>
            {% endfor %}
        </div>
    </div>
    {% if field.allow_custom %}
        <script>
            $(document).ready(function() {
                $('div#{{field.name}}').dropdown({
                  allowAdditions: true
                })
            });
        </script>
    {% endif %}
{% endmacro %}

{# Render a field for the form #}
{% macro render_form_field(field, extra_classes='') %}
    {% if field.type == 'Radio Field' %}
        {% set extra_classes = extra_classes + ' grouped fields' %}
    {% endif %}
    <div class="field {% if field.errors %}error{% endif %} {{ extra_classes }}">
        {{ render_form_input(field) }}
        {% if field.errors %}
            <div class="ui red pointing label">
                {{ field.errors[0] | safe }}
            </div>
        {% endif %}
    </div>
{% endmacro %}

{% macro render_form_input(field) %}
    {% if field.widget.input_type == 'checkbox' %}
        <div class="ui checkbox">
            {{ field }}
            {{ field.label }}
        </div>
    {% elif field.type == 'RadioField' %}
        {{ field.label }}
        {% for item in field %}
            <div class="ui radio checkbox">
                {{ item }}
                {{ item.label }}
            </div>
        {% endfor %}
    {% elif field.type == 'SubmitField' %}
        {{ field(class='ui button') }}
    {% elif field.type == 'FormField' %}
        {{ render_form(field) }}
    {% elif field.type == 'CustomSelectField' %}
        {{ render_custom_select(field) }}
    {% else %}
        {{ field.label }}
        {% if field.description %}
            <div class="ui pointing below label">
                {{ field.description }}
            </div>
        {% endif %}
        {{ field(placeholder=field.label.text) }}
    {% endif %}
{% endmacro %}

app/templates/macros/nav_macros.html
{# This macro is called on the user dashboards. In this case the administrator dashboard
   at the route admin.index
#}

{% macro render_menu_items(endpoints) %}
    {% for endpoint, name, icon in endpoints %}
        <a class="item {% if request.endpoint == endpoint %}active{% endif %}" href="{{ url_for(endpoint) }}">
            {% if icon %}
                <i class="{{ icon }} icon"></i>
            {% endif %}
            {{ name | safe }}
        </a>
    {% endfor %}
{% endmacro %}

{# This is called for all users (including anonymous users). It renders the basic left side of the 
   navigation bar. In the default case, the left hand side will read 'Flask-Base'. In the logged in
   admin case, there will also be an item that links to admin/ route. I have added an example use of
   render_menu_items.
#}

{% macro header_items(current_user) %}
    {% set endpoints = [
      ('main.index', config.APP_NAME, 'home'),
      ('main.about', 'About', 'info')
    ]%}
    {% set user = [] %}
    {% if current_user.is_authenticated %}
      {% set user = ([(current_user.role.index + '.index', current_user.role.name + ' Dashboard', 'user')]) %}
    {% endif %} 
    {{ render_menu_items( endpoints +  user ) }}
{% endmacro %}

{# This renders the right hand side of the navigation bar. If the user is logged in, it links to 
   manage their account and logout (account routes). Otherwise, it links to register and login.
#}
{% macro account_items(current_user) %}
    {% if current_user.is_authenticated %}
      {% set endpoints = [
        ('account.manage', 'Your Account', 'settings'),
        ('account.logout', 'Log out', 'sign out')
      ] %}
      {{ render_menu_items(endpoints) }}
    {% else %}
      {% set endpoints = [
        ('account.register', 'Register', 'list layout'),
        ('account.login', 'Log In', 'sign in')
      ] %}
      {{ render_menu_items(endpoints) }}
    {% endif %}
{% endmacro %}

{% macro mobile_nav(current_user, dropdown=None) %}
    <div class="mobile only row">
        <div class="ui fixed inverted black main menu">
            {{ header_items(current_user) }}
            <div class="right menu">
                <a class="icon item" id="open-nav"><i class="sidebar icon"></i></a>
            </div>
        </div>

        {# The menu items which will be shown when open-nav is clicked #}
        <div class="ui fixed vertical fluid menu">
          {{ account_items(current_user) }}
          {{ create_dropdown(dropdown) }}
        </div>
    </div>
{% endmacro %}

{% macro create_dropdown(dropdown) %}
  {% for item in dropdown %}
    {% if item | length == 3 %}
      {{ render_menu_items([item]) }}
    {% elif item | length == 2 %}
      <div class="ui dropdown item" onClick="changeMenu(this)">{{ item[0] }} <i class="dropdown icon"></i>
        <div class="inverted black menu">
          {{ create_dropdown(item[1]) }}
        </div>
      </div>
    {% endif %}
  {% endfor %}
{% endmacro %}

{% macro desktop_nav(current_user, dropdown=None) %}
    <div class="computer tablet only row">
        <div class="ui fixed inverted black main menu">
            <div class="ui container">
                {{ header_items(current_user) }}
                {{ create_dropdown(dropdown) }}
                <div class="right menu">
                    {{ account_items(current_user) }}
                </div>
            </div>
        </div>
    </div>
{% endmacro %}

{% macro render_nav(current_user, dropdown=[]) %}
    <nav class="ui navigation grid {% if endpoints %}has-submenu{% endif %}">
        {{ mobile_nav(current_user, dropdown=dropdown) }}
        {{ desktop_nav(current_user, dropdown=dropdown) }}
    </nav>
{% endmacro %}

app/templates/macros/page_macros.html
{% macro render_inline_editor(editable_html_obj, current_user) %}
    <div id="editor-{{ editable_html_obj.editor_name }}" contenteditable="false">
        {{ editable_html_obj.value|safe }}
    </div>

    {% if current_user.is_admin() %}
       <button class="ui button start-edit">
        Edit
       </button>
       <button class="ui primary button end-edit">
        Save
       </button>
    {% endif %}

    <script>
    var editorIDName = "editor-{{ editable_html_obj.editor_name }}";
    $(document).ready(function() {
        {% if current_user.is_admin() %}
            $(".end-edit").hide();
        {% endif %}
        $(".start-edit").click(function() {
            CKEDITOR.disableAutoInline = true;
            var editor = CKEDITOR.inline(editorIDName, {
                startupFocus: true,
                autoGrow_onStartup: true
            });
            $(".start-edit").hide();
            $(".end-edit").show();
            $("#" + editorIDName).attr("contenteditable","true");
        });

        $(".end-edit").click(function() {
            if ( CKEDITOR.instances[editorIDName] ) {
                var json_data = {
                    csrf_token: "{{ csrf_token() }}",
                    editor_name: "{{ editable_html_obj.editor_name }}",
                    edit_data: CKEDITOR.instances[editorIDName].getData(),
                };
                $.post("{{ url_for('admin.update_editor_contents') }}", json_data);
                CKEDITOR.instances[editorIDName].destroy();
            }
            $(".end-edit").hide();
            $(".start-edit").show();
            $("#" + editorIDName).attr("contenteditable","false");
        });
    });
    </script>

{% endmacro %}